// Code generated by mockery v1.0.0. DO NOT EDIT.

package dvow

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIOverwritingOps is an autogenerated mock type for the IOverwritingOps type
type MockIOverwritingOps struct {
	mock.Mock
}

// ExtractOverwritingStorage provides a mock function with given fields: ctx
func (_m *MockIOverwritingOps) ExtractOverwritingStorage(ctx context.Context) Storage {
	ret := _m.Called(ctx)

	var r0 Storage
	if rf, ok := ret.Get(0).(func(context.Context) Storage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Storage)
		}
	}

	return r0
}

// GetOverwrittenValue provides a mock function with given fields: ctx, name
func (_m *MockIOverwritingOps) GetOverwrittenValue(ctx context.Context, name string) Value {
	ret := _m.Called(ctx, name)

	var r0 Value
	if rf, ok := ret.Get(0).(func(context.Context, string) Value); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Value)
		}
	}

	return r0
}
