// Code generated by mockery v1.0.0. DO NOT EDIT.

package dvow

import mock "github.com/stretchr/testify/mock"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// Get provides a mock function with given fields: name
func (_m *MockStorage) Get(name string) Value {
	ret := _m.Called(name)

	var r0 Value
	if rf, ok := ret.Get(0).(func(string) Value); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Value)
		}
	}

	return r0
}
